version: "3.8"

services:
  psql-db:
    container_name: psql-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - psql:/var/lib/postgresql/data:rw
      - ./psql/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - 5432:5432

  engine:
    build:
      context: engine
      dockerfile: deploy/Dockerfile
    command: sh -c "./scripts/wait-for.sh psql-db:5432 && ./bin/migrate up && ./bin/server"
    volumes:
      - ./engine/.env:/go/src/app/.env
    ports:
      - 2513
    depends_on:
      - psql-db

  user-manager:
    build:
      context: user-manager
      dockerfile: deploy/Dockerfile
    command: sh -c "./scripts/wait-for.sh psql-db:5432 && ./bin/migrate up && ./bin/server"
    volumes:
      - ./user-manager/.env:/go/src/app/.env
    ports:
      - 8080
    depends_on:
      - psql-db

volumes:
  psql:
