version: "3.8"

services:
  psql-db:
    container_name: psql-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - psql:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

  engine:
    build:
      context: engine
      dockerfile: deploy/Dockerfile
    volumes:
      - ./engine/.env:/go/src/app/.env
    ports:
      - 2513
    depends_on:
      - psql-db

  # user-controller:
  #   container_name: user-controller
  #   pull_policy: always
  #   restart: always
  #   command: sh -c "./scripts/wait-for.sh psql-db:5432 && ./bin/migrate up && ./bin/server"
  #   volumes:
  #     - /etc/tie/cc/env.user-controller:/go/src/app/.env
  #   depends_on:
  #     - psql-db

volumes:
  psql: