# ------------КОММАНДЫ ДЛЯ РАЗРАБОТКИ---------------

.PHONY: server
# Запуск сервера
server:
	go run ./cmd/server/main.go

.PHONY: tgbot
# Запуск телеграм бота
tgbot:
	go run ./cmd/tgbot/main.go

.PHONY: testbox
# Запуск тестового приложения
testbox:
	go run ./cmd/testbox/main.go

# --------------------------------------------------